/*
MIT License

Copyright (c) 2018-2019 Syoyo Fujita

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#include "cyhair-writer.h"

#include <cassert>
#include <cstring>
#include <sstream>
#include <iostream>

namespace cyhair_writer
{

    //
    // Serialize curves as CyHair format.
    //
    std::string SerializeAsCyHair(
        std::vector<float>& points,
        std::vector<float>& radiuss,
        std::vector<float>& texcoords,
        std::vector<uint32_t>& num_points,
        const bool _export_radiuss,
        const bool _export_texcoords)
    {
        CyhairHeader header;

        if (sizeof(header) != 128)
        {
            std::cerr << "header size mismatch." << std::endl;
            return std::string();
        }

        const bool export_radiuss = _export_radiuss && (radiuss.size() > 0);
        const bool export_texcoords = _export_texcoords && (texcoords.size() > 0);

        header.signagure[0] = 'H';
        header.signagure[1] = 'A';
        header.signagure[2] = 'I';
        header.signagure[3] = 'R';

        // 0x01 = has_segments
        // 0x02 = has_points
        // 0x04 = has_thickness
        // 0x08 = has_transparency
        // 0x10 = has_color
        // 0x20 = has_texcoords(my extension)
        header.flags = 0x1 | 0x2;

        if (export_radiuss)
        {
            header.flags |= 0x04;
        }

        if (export_texcoords)
        {
            header.flags |= 0x20;
        }

        header.d_segments = 0;        // no default segments.
        header.d_thickness = 1.0f;    // FIXME(syoyo)
        header.d_transparency = 0.5f; // FIXME(syoyo)
        header.d_color[0] = 1.0f;     // FIXME(syoyo)
        header.d_color[1] = 1.0f;     // FIXME(syoyo)
        header.d_color[2] = 1.0f;     // FIXME(syoyo)

        header.hair_count = num_points.size();
        header.point_count = points.size() / 3; // XYZ

        std::string info("Generated by XGen Spline converter.");
        assert(info.size() < (CYHAIR_INFO_HEADER_SIZE - 1));
        memcpy(header.info, info.data(), info.size());

        std::stringstream ss;

        // strands = points - 1
        std::vector<uint16_t> num_strands;
        for (size_t i = 0; i < num_points.size(); i++)
        {
            assert(num_points[i] > 0);
            assert(num_points[i] < std::numeric_limits<uint16_t>::max());
            num_strands.push_back(uint16_t(num_points[i] - 1));
        }

        // write header.
        ss.write(reinterpret_cast<const char*>(&header), sizeof(header));

        // write strands.
        ss.write(reinterpret_cast<const char*>(num_strands.data()), num_strands.size() * sizeof(uint16_t));

        // write points.
        ss.write(reinterpret_cast<const char*>(points.data()), points.size() * sizeof(float));

        if (export_radiuss)
        {
            std::cout << "export widths : " << radiuss.size() << std::endl;
            ss.write(reinterpret_cast<const char*>(radiuss.data()), radiuss.size() * sizeof(float));
        }

        if (export_texcoords)
        {
            std::cout << "export texcoords" << std::endl;
            ss.write(reinterpret_cast<const char*>(texcoords.data()), texcoords.size() * sizeof(float));
        }

        return ss.str();
    }

} // namespace cyhair_writer
